### ISSUE TITLE
Run on go1

### ISSUE THREAD

**Issue by boyuandeng** [antonilo/vision_locomotion#6]
hi! @antonilo 
i had finished all settings, but i got a error when i try to roslaunch
i had run with  `roslaunch agile_locomotion cms_ros.launch`
but when i want run next command
`rostopic pub /agile_locomotion/walk std_msgs/Empty "{}" -1 `
i got this.:
`process[agile_locomotion-1]: started with pid [3849]
[ INFO] [1691047835.232579541]: Loading parameters...
[ INFO] [1691047835.241519694]: [/agile_locomotion] base_path = /home/ubuntu/cms_ws/catkin_cms/src/agile_locomotion/controller/models/blind
[ INFO] [1691047835.244527230]: [/agile_locomotion] vision_path = /home/ubuntu/cms_ws/catkin_cms/src/agile_locomotion/controller/models/vision
[ INFO] [1691047835.248558267]: [/agile_locomotion] general/policy_id = 1200
[ INFO] [1691047835.251827438]: [/agile_locomotion] general/Kp = 46
[ INFO] [1691047835.256704960]: [/agile_locomotion] general/Kd = 0.8
[ INFO] [1691047835.259685091]: [/agile_locomotion] general/force_threshold = 25
[ INFO] [1691047835.262763905]: [/agile_locomotion] general/hip_joint_angle = 0.45
[ INFO] [1691047835.266439505]: [/agile_locomotion] general/lin_speed = 0
[ INFO] [1691047835.270164803]: [/agile_locomotion] general/max_lin_speed = 0.5
[ INFO] [1691047835.273675256]: [/agile_locomotion] general/ang_speed = 0
[ INFO] [1691047835.278020437]: [/agile_locomotion] general/max_ang_speed = 0.4
[ INFO] [1691047835.281052126]: [/agile_locomotion] general/tsteps = 50
[ INFO] [1691047835.284004734]: [/agile_locomotion] general/init_steps = 0
[ INFO] [1691047835.287700917]: [/agile_locomotion] general/testing = 0
[ INFO] [1691047835.290427720]: [/agile_locomotion] general/log = 0
[ INFO] [1691047835.293465994]: [/agile_locomotion] general/latent_size = 10
[ INFO] [1691047835.297873048]: [/agile_locomotion] general/obDim = 42
[ INFO] [1691047835.301422716]: [/agile_locomotion] visual_pred/n_g1 = 1
[ INFO] [1691047835.304696850]: [/agile_locomotion] visual_pred/using_vision = 1
[ INFO] [1691047835.304771820]: Parameters Loaded
[ INFO] [1691047835.371162025]: Ros is Ready
UDP Initialized. socketfd: 11   Port: 8080
/home/ubuntu/cms_ws/catkin_cms/src/agile_locomotion/controller/models/blind/mlp_1200.pt
/home/ubuntu/cms_ws/catkin_cms/src/agile_locomotion/controller/models/blind/mean1200.csv
/home/ubuntu/cms_ws/catkin_cms/src/agile_locomotion/controller/models/blind/var1200.csv
Model loaded from /home/ubuntu/cms_ws/catkin_cms/src/agile_locomotion/controller/models/blind/mlp_1200.pt
read 2170 elements
-0.0239535 0.0439375 -0.12916 0.758832 -1.66217 0.0613242 0.842654 -1.70348 -0.0228252 1.0097 -1.61146 0.0425482 0.926225 -1.63034 -0.034175 -0.00407411 -0.0600386 0.0178517 0.00547594 -0.0474542 -0.00861305 0.0663182 -0.0694604 0.0182749 0.0531053 -0.0878771 -0.398974 -0.169958 -0.319639 0.254109 0.00548921 -0.370061 -0.121593 0.459505 -0.31236 0.168439 0.309663 -0.331397 -0.0870205 0.000291746 -0.0870205 0.000291746 -0.0239535 0.0439375 -0.12916 0.758832 -1.66217 0.0613242 0.842654 -1.70348 -0.0228252 1.0097 -1.61146 0.0425482 0.926225 -1.63034 -0.034175 -0.00407411 -0.0600386 0.0178517 0.00547594 -0.0474542 -0.00861305 0.0663182 -0.0694604 0.0182749 0.0531053 -0.0878771 -0.398974 -0.169958 -0.319639 0.254109 0.00548921 -0.370061 -0.121593 0.459505 -0.31236 0.168439 0.309663 -0.331397 -0.0870205 0.000291746 -0.0870205 0.000291746 -0.0239535 0.0439375 -0.12916 0.758832 -1.66217 0.0613242 0.842654 -1.70348 -0.0228252 1.0097 -1.61146 0.0425482 0.926225 -1.63034 -0.034175 -0.00407411 ...
read 2170 elements
0.0154548 0.0116776 0.0184138 0.049594 0.0278942 0.0181977 0.0558888 0.0309958 0.0225005 0.0418531 0.0228641 0.0146581 0.0493584 0.0201657 9.36695 9.56942 17.3742 9.20628 8.86184 16.3252 9.10493 8.82635 13.4025 8.22132 10.5601 12.9502 0.155069 0.308698 0.310683 0.15197 0.308596 0.304845 0.177323 0.208968 0.188846 0.141731 0.282548 0.225084 0.0130294 0.0251278 0.0130294 0.0251278 0.0154548 0.0116776 0.0184138 0.049594 0.0278942 0.0181977 0.0558888 0.0309958 0.0225005 0.0418531 0.0228641 0.0146581 0.0493584 0.0201657 9.36695 9.56942 17.3742 9.20628 8.86184 16.3252 9.10493 8.82635 13.4025 8.22132 10.5601 12.9502 0.155069 0.308698 0.310683 0.15197 0.308596 0.304845 0.177323 0.208968 0.188846 0.141731 0.282548 0.225084 0.0130294 0.0251278 0.0130294 0.0251278 0.0154548 0.0116776 0.0184138 0.049594 0.0278942 0.0181977 0.0558888 0.0309958 0.0225005 0.0418531 0.0228641 0.0146581 0.0493584 0.0201657 9.36695 9.56942 ...
/home/ubuntu/cms_ws/catkin_cms/src/agile_locomotion/controller/models/vision/mlp_1200.pt
/home/ubuntu/cms_ws/catkin_cms/src/agile_locomotion/controller/models/vision/mean1200.csv
/home/ubuntu/cms_ws/catkin_cms/src/agile_locomotion/controller/models/vision/var1200.csv
Model loaded from /home/ubuntu/cms_ws/catkin_cms/src/agile_locomotion/controller/models/vision/mlp_1200.pt
read 2170 elements
-0.0324568 0.0626056 -0.131 0.758529 -1.62647 0.0651591 0.874964 -1.63657 -0.0282134 0.982228 -1.59791 0.0457578 0.935868 -1.62761 -0.0470667 0.0010261 -0.087897 0.0269814 0.0194737 -0.0693525 -0.0140214 0.0800436 -0.0956743 0.0292944 0.0643533 -0.0960237 -0.418023 -0.208554 -0.306892 0.266959 0.0304787 -0.302846 -0.131643 0.419291 -0.289692 0.190893 0.348675 -0.253107 -0.0678066 0.000747435 -0.0678066 0.000747435 -0.0324568 0.0626056 -0.131 0.758529 -1.62647 0.0651591 0.874964 -1.63657 -0.0282134 0.982228 -1.59791 0.0457578 0.935868 -1.62761 -0.0470667 0.0010261 -0.087897 0.0269814 0.0194737 -0.0693525 -0.0140214 0.0800436 -0.0956743 0.0292944 0.0643533 -0.0960237 -0.418023 -0.208554 -0.306892 0.266959 0.0304787 -0.302846 -0.131643 0.419291 -0.289692 0.190893 0.348675 -0.253107 -0.0678066 0.000747435 -0.0678066 0.000747435 -0.0324568 0.0626056 -0.131 0.758529 -1.62647 0.0651591 0.874964 -1.63657 -0.0282134 0.982228 -1.59791 0.0457578 0.935868 -1.62761 -0.0470667 0.0010261 ...
read 2170 elements
0.0190809 0.0259078 0.0207875 0.0494777 0.0357764 0.0196531 0.058697 0.0405954 0.0255469 0.0490561 0.0229684 0.019187 0.0502801 0.0277285 10.2164 10.5676 19.035 9.78872 9.99721 19.3128 10.1362 9.79533 14.7176 9.48268 12.1181 15.7794 0.161398 0.329998 0.339974 0.157455 0.323308 0.340018 0.193207 0.26286 0.202941 0.171694 0.297858 0.294014 0.00741218 0.0200035 0.00741218 0.0200035 0.0190809 0.0259078 0.0207875 0.0494777 0.0357764 0.0196531 0.058697 0.0405954 0.0255469 0.0490561 0.0229684 0.019187 0.0502801 0.0277285 10.2164 10.5676 19.035 9.78872 9.99721 19.3128 10.1362 9.79533 14.7176 9.48268 12.1181 15.7794 0.161398 0.329998 0.339974 0.157455 0.323308 0.340018 0.193207 0.26286 0.202941 0.171694 0.297858 0.294014 0.00741218 0.0200035 0.00741218 0.0200035 0.0190809 0.0259078 0.0207875 0.0494777 0.0357764 0.0196531 0.058697 0.0405954 0.0255469 0.0490561 0.0229684 0.019187 0.0502801 0.0277285 10.2164 10.5676 ...
/home/ubuntu/cms_ws/catkin_cms/src/agile_locomotion/controller/models/blind/prop_encoder_1200.pt
/home/ubuntu/cms_ws/catkin_cms/src/agile_locomotion/controller/models/blind/mean1200.csv
/home/ubuntu/cms_ws/catkin_cms/src/agile_locomotion/controller/models/blind/var1200.csv
Model loaded from /home/ubuntu/cms_ws/catkin_cms/src/agile_locomotion/controller/models/blind/prop_encoder_1200.pt
read 2170 elements
-0.0239535 0.0439375 -0.12916 0.758832 -1.66217 0.0613242 0.842654 -1.70348 -0.0228252 1.0097 -1.61146 0.0425482 0.926225 -1.63034 -0.034175 -0.00407411 -0.0600386 0.0178517 0.00547594 -0.0474542 -0.00861305 0.0663182 -0.0694604 0.0182749 0.0531053 -0.0878771 -0.398974 -0.169958 -0.319639 0.254109 0.00548921 -0.370061 -0.121593 0.459505 -0.31236 0.168439 0.309663 -0.331397 -0.0870205 0.000291746 -0.0870205 0.000291746 -0.0239535 0.0439375 -0.12916 0.758832 -1.66217 0.0613242 0.842654 -1.70348 -0.0228252 1.0097 -1.61146 0.0425482 0.926225 -1.63034 -0.034175 -0.00407411 -0.0600386 0.0178517 0.00547594 -0.0474542 -0.00861305 0.0663182 -0.0694604 0.0182749 0.0531053 -0.0878771 -0.398974 -0.169958 -0.319639 0.254109 0.00548921 -0.370061 -0.121593 0.459505 -0.31236 0.168439 0.309663 -0.331397 -0.0870205 0.000291746 -0.0870205 0.000291746 -0.0239535 0.0439375 -0.12916 0.758832 -1.66217 0.0613242 0.842654 -1.70348 -0.0228252 1.0097 -1.61146 0.0425482 0.926225 -1.63034 -0.034175 -0.00407411 ...
read 2170 elements
0.0154548 0.0116776 0.0184138 0.049594 0.0278942 0.0181977 0.0558888 0.0309958 0.0225005 0.0418531 0.0228641 0.0146581 0.0493584 0.0201657 9.36695 9.56942 17.3742 9.20628 8.86184 16.3252 9.10493 8.82635 13.4025 8.22132 10.5601 12.9502 0.155069 0.308698 0.310683 0.15197 0.308596 0.304845 0.177323 0.208968 0.188846 0.141731 0.282548 0.225084 0.0130294 0.0251278 0.0130294 0.0251278 0.0154548 0.0116776 0.0184138 0.049594 0.0278942 0.0181977 0.0558888 0.0309958 0.0225005 0.0418531 0.0228641 0.0146581 0.0493584 0.0201657 9.36695 9.56942 17.3742 9.20628 8.86184 16.3252 9.10493 8.82635 13.4025 8.22132 10.5601 12.9502 0.155069 0.308698 0.310683 0.15197 0.308596 0.304845 0.177323 0.208968 0.188846 0.141731 0.282548 0.225084 0.0130294 0.0251278 0.0130294 0.0251278 0.0154548 0.0116776 0.0184138 0.049594 0.0278942 0.0181977 0.0558888 0.0309958 0.0225005 0.0418531 0.0228641 0.0146581 0.0493584 0.0201657 9.36695 9.56942 ...
[ INFO] [1691047839.430245843]: Received startExecutionCallback message!
[Loop Start] named: udp_send period: 2(ms)
run at cpu: 3
[Loop Start] named: udp_recv period: 2(ms)
run at cpu: 3
agile_locomotion: ../nptl/pthread_mutex_lock.c:81: __pthread_mutex_lock: Assertion mutex->__data.__owner == 0' failed.
[agile_locomotion-1] process has died [pid 3849, exit code -6, cmd /home/ubuntu/cms_ws/catkin_cms/devel/lib/agile_locomotion/agile_locomotion __name:=agile_locomotion __log:=/home/ubuntu/.ros/log/ac1a1ae2-8feb-11ec-b887-e45f01ce12ec/agile_locomotion-1.log].
log file: /home/ubuntu/.ros/log/ac1a1ae2-8feb-11ec-b887-e45f01ce12ec/agile_locomotion-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete`

i guess it caused by memory lock, but i have changed /etc/security/limis.conf 
my `/etc/security/limis.conf  is here:

`ubuntu soft memlock unlimited
ubuntu hard memlock unlimited
ubuntu soft nice eip
ubuntu hard nice eip
ubuntu soft rtprio 99
ubuntu hard rtprio 99`

**Comment by antonilo** [comment]
can you try to first go in superuser mode (just type su) and try again?

**Comment by boyuandeng** [comment]
@antonilo  thanks anto!
hello everyone, I finished the work that deploy this repo on go1(NX), here is the video.

I also pushed go1_description(simple but suitable for the specified version of raisim with rl_locomotion) , you can feel free to use it.

then, I will improve the performance.

I will push my code in my repo(maybe in October)

**Comment by boyuandeng** [comment]
https://github.com/antonilo/vision_locomotion/assets/48037435/06b1115a-3f39-42c6-be57-bd64dfa8c9de
